import {openCuration,openFilters,closeFilters,closeInspector} from "./workspace-helper.mjs";
// Synthetic, GET-only fixture reads plus local custom-tag mock mutations. No external API/model.
import assert from "node:assert/strict";
import { chromium } from "playwright";
import { createFixtureState, startFixtureServer } from "./fixture-server.mjs";
import { taxonomyV2 } from "./fixture-data.mjs";
const fixture = createFixtureState({ count: 30 });
const item = fixture.items.find(item => item.curation_status === "inbox");
const identity = {schema_version:1,content_revision:1,body_revision:1,personal_revision:1,latest_decision_id:1,latest_entity_revision:1};
item.cache_identity = identity;
const selection = {topics:["llm"],resource_kinds:["reference"],content_functions:["method"],carriers:[],affordances:[]};
item.classification = {...item.classification,...selection}; item.status="completed";
const catalog = {...taxonomyV2(),resource_kinds:[{id:"reference",label:"参考资料",active:true}]};
const payload = {id:item.id,revision:1,content_revision:1,decision_id:1,selection,automatic:selection,custom_tags:[],state:{fields:{}}};
const {server,url} = await startFixtureServer({state:fixture});
const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || "/usr/bin/google-chrome",args:["--no-sandbox"]});
const context = await browser.newContext({viewport:{width:1280,height:900}});
const page = await context.newPage(); const errors=[]; page.on("pageerror",error=>errors.push(error.message));
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const send=(route,value,status=200)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify(value)}).catch(()=>{});
let tags=0,customReads=0,counts=0,identities=0,tagDelay=0,tagFailure=false,readingDelay=0;
let custom=[]; const readingCalls=[];let identityDelay=0,identityChanged=false,backstageReads=0,overviewReads=0,holdBackstage=false,releaseBackstage=null,backstageCombined=true;
page.on("request",request=>{if(new URL(request.url()).pathname==="/api/overview")overviewReads++;});
await context.addInitScript(()=>{
  const original=window.fetch; window.fetchAborts=[]; window.objectRevokes=0;
  window.fetch=(url,options={})=>{options.signal?.addEventListener("abort",()=>window.fetchAborts.push(String(url)),{once:true});return original(url,options);};
  const revoke=URL.revokeObjectURL;URL.revokeObjectURL=url=>{window.objectRevokes++;revoke(url);};
});
await context.route("**/api/v2-taxonomy",route=>send(route,catalog));
await context.route("**/api/custom-tags",route=>{
  if(route.request().method()==="GET"){customReads++;return send(route,{tags:custom});}
  custom=[{id:"local",tag_ref:"custom/default/local",label:"我的实验",revision:1,status:"active"}]; return send(route,{tag:custom[0]});
});
await context.route("**/api/tag-counts?*",route=>{counts++;return send(route,{total:1,topics:[{id:"llm",count:1}],resource_kinds:[],custom_tags:[]});});
await context.route(/\/api\/bookmarks\/\d+\/tags$/,async route=>{tags++;await pause(tagDelay);return send(route,tagFailure?{error:"backend_error"}:payload,tagFailure?503:200);});
await context.route(/\/api\/bookmarks\/\d+\/reading(?:\?|$)/,async route=>{
  const id=Number(new URL(route.request().url()).pathname.split("/")[3]);readingCalls.push(id);
  await pause(readingDelay);
  const source=fixture.items.find(entry=>entry.id===id)||item;
  const {v2,entities,classificationJob,...detail}=source;
  return send(route,{version:1,detail:{...detail,id,content_loaded:true,cache_identity:identity},selection:{available:true,id,revision:1,selection},entities:{available:true,id,revision:1,state:"completed",entities:[]}});
});
await context.route(/\/api\/bookmarks\/\d+\/identity$/,async route=>{identities++;await pause(identityDelay);return send(route,{id:item.id,status:"completed",cache_identity:identityChanged?{...identity,body_revision:99}:identity,updated_at:item.updated_at});});
await context.route("**/api/backstage",async route=>{backstageReads++;if(holdBackstage)await new Promise(resolve=>{releaseBackstage=resolve;});else await pause(250);const payload={counts:{total:30},attention:[],overview:{views:{all:30,inbox:12},counts:{total:30},attention:0,queued:0}};if(!backstageCombined)delete payload.overview;return send(route,payload);});
let checks=0;const ok=message=>{checks++;console.log("ok   "+message);};
async function wait(predicate){for(let i=0;i<200;i++){if(await predicate())return;await pause(25);}throw new Error("condition timeout");}
try{
  await page.clock.install();
  await page.goto(`${url}/bookmarks/${item.id}`);
  await page.waitForFunction(()=>document.querySelector("#body-loading")?.hidden);
  await page.waitForFunction(()=>document.querySelector("#list-pane")?.dataset.loading === "false");
  await pause(500);
  assert.equal(tags,0);assert.equal(customReads,1);assert.equal(counts,0);
  assert.equal(await page.locator(".tag-system-row").count(),0);assert.match(await page.locator("#curate-summary-tags").textContent(),/参考资料/);
  ok("collapsed reader uses effective summary without tags/facets; one shared custom catalog read");
  const thumbnails=await page.locator("#rows .row-thumb img").evaluateAll(images=>images.map(image=>image.dataset.imageSource));assert.ok(thumbnails.length>0);assert.ok(thumbnails.every(source=>source.includes("privacy=1&size=160")));ok("list thumbnails use the bounded private thumbnail endpoint");
  await openCuration(page);
  await page.locator('.tag-system-row[data-dimension="topics"]').waitFor();assert.equal(tags,1);
  tagDelay=250;
  await page.evaluate(async id=>{const store=await import('/assets/js/store.js');const tag=await import('/assets/js/tag-system.js');store.getItem(id).cache_identity.personal_revision++;for(let i=0;i<5;i++)tag.refreshTagSystem(id);},item.id);
  await wait(()=>tags===2);await pause(350);assert.equal(tags,2);assert.equal(customReads,1);
  ok("repeated tag refresh coalesces one request and reuses custom catalog");
  await page.evaluate(async id=>{const store=await import('/assets/js/store.js');const tag=await import('/assets/js/tag-system.js');store.getItem(id).cache_identity.personal_revision++;tag.refreshTagSystem(id);},item.id);
  await wait(()=>tags===3);
  await page.evaluate(async()=>{const tag=await import('/assets/js/tag-system.js');document.querySelector('#curate').open=false;tag.suspendTagSystem();document.querySelector('#curate').open=true;});
  await wait(()=>tags===4);await pause(350);
  assert.equal(await page.evaluate(async id=>(await import('/assets/js/tag-system.js')).tagSystemReady(id),item.id),true);
  ok("close and immediate reopen resumes an aborted tag load");
  tagFailure=true;const failedBefore=tags;
  await page.evaluate(async id=>{const store=await import('/assets/js/store.js');store.getItem(id).cache_identity.personal_revision++;(await import('/assets/js/tag-system.js')).refreshTagSystem(id);},item.id);
  await pause(900);assert.equal(tags,failedBefore+1);tagFailure=false;tagDelay=0;
  ok("failed tag refresh keeps previous data without recursive retries");
  const taxonomyEvents=await page.evaluate(async()=>{const store=await import('/assets/js/store.js');const tax=await import('/assets/js/taxonomy.js');const {api}=await import('/assets/js/api.js');let count=0;store.on('taxonomy',()=>count++);await Promise.all([tax.loadCustomTags(),tax.loadCustomTags()]);await api.createCustomTag({label:'我的实验'});await Promise.all([tax.loadCustomTags(),tax.loadCustomTags()]);await tax.loadCustomTags();return count;});
  assert.equal(customReads,2);assert.equal(taxonomyEvents,1);ok("custom mutation invalidates one shared catalog and broadcasts only changed values");
  await closeInspector(page);await openFilters(page);
  await page.locator('details[data-group="topics"] > summary').click();await wait(()=>counts===1);
  await page.locator('details[data-group="topics"] > summary').click();
  await page.evaluate(async()=>{const {state}=await import('/assets/js/store.js');state.filters.topics=['llm'];(await import('/assets/js/sidebar.js')).renderSidebar();});await pause(300);assert.equal(counts,1);
  await page.locator('details[data-group="topics"] > summary').click();await wait(()=>counts===2);
  ok("closed facet groups defer requests and reopening fetches the current query");
  await closeFilters(page);await page.setViewportSize({width:375,height:812});
  await page.waitForFunction(()=>document.querySelector("#app").dataset.layout==="narrow");
  await page.locator("#detail-back").click();
  const hiddenCounts=counts;
  await page.evaluate(async()=>{const {state}=await import('/assets/js/store.js');state.filters.topics=['llm','eng'];(await import('/assets/js/sidebar.js')).renderSidebar();});await pause(250);assert.equal(counts,hiddenCounts);
  await openFilters(page);await wait(()=>counts===hiddenCounts+1);
  await page.keyboard.press('Escape');ok("a hidden mobile sidebar defers counts even when its topic group is open");
  await page.evaluate(async()=>{const {state}=await import('/assets/js/store.js');state.route={name:'library',id:0};(await import('/assets/js/detail.js')).syncReaderVisibility();});
  const beforeHidden=identities;await page.clock.fastForward(65_000);await pause(150);assert.equal(identities,beforeHidden);
  ok("mobile hidden reader does not poll identity");
  readingDelay=450;
  await page.evaluate(async id=>{const {state,getItem}=await import('/assets/js/store.js');getItem(id).content_loaded=false;state.route={name:'bookmark',id};(await import('/assets/js/detail.js')).syncReaderVisibility();},item.id);
  await wait(()=>readingCalls.filter(id=>id===item.id).length>=2);
  const beforeResume=readingCalls.length;
  await page.evaluate(async id=>{const {state}=await import('/assets/js/store.js');const detail=await import('/assets/js/detail.js');state.route={name:'library',id:0};detail.syncReaderVisibility();state.route={name:'bookmark',id};detail.syncReaderVisibility();},item.id);
  await wait(()=>readingCalls.length>beforeResume);await pause(550);
  assert.equal(await page.locator('#body-loading').isVisible(),false);ok("hide and immediate show restarts cancelled article without waiting for polling");
  identityDelay=250;identityChanged=true;const identityBefore=identities;
  await page.clock.fastForward(16_000);await wait(()=>identities>identityBefore);
  await page.evaluate(async()=>{const {state}=await import('/assets/js/store.js');state.route={name:'library',id:0};(await import('/assets/js/detail.js')).syncReaderVisibility();});
  const lateBefore=readingCalls.length;await pause(400);assert.equal(readingCalls.length,lateBefore);
  ok("late identity response cannot restart a hidden article");
  const overviewBefore=overviewReads;
  await page.evaluate(async()=>{const {state}=await import('/assets/js/store.js');state.route={name:'backstage',id:0};const back=await import('/assets/js/backstage.js');await Promise.all([back.refresh(),back.refresh(),back.refresh()]);});
  assert.equal(backstageReads,1);await pause(50);assert.equal(overviewReads,overviewBefore);
  assert.equal(await page.evaluate(async()=>(await import('/assets/js/store.js')).state.overview.views.all),30);
  ok("backstage refresh shares one summary and reuses overview without another GET");
  holdBackstage=true;
  await page.evaluate(async()=>{window.heldBackstage=(await import('/assets/js/backstage.js')).refresh();});
  await wait(()=>releaseBackstage!==null);
  await page.evaluate(()=>document.querySelector('#status-seg [data-status="kept"]').click());
  await page.getByText('已移到「精选」',{exact:true}).waitFor(); // emitted only after pendingCuration--
  const afterMutation=await page.evaluate(async()=>(await import('/assets/js/store.js')).state.overview.views.inbox);
  assert.equal(afterMutation,11);
  releaseBackstage();await page.evaluate(()=>window.heldBackstage);
  assert.equal(await page.evaluate(async()=>(await import('/assets/js/store.js')).state.overview.views.inbox),afterMutation);
  ok("late backstage overview cannot replace counts after a local mutation has finished");
  holdBackstage=false;backstageCombined=false;
  await page.evaluate(async()=>(await import('/assets/js/backstage.js')).refresh());
  await page.evaluate(async()=>{window.trailingOverviewApplied=false;(await import('/assets/js/store.js')).on('overview',()=>{window.trailingOverviewApplied=true;});});
  const trailingBefore=overviewReads;await page.clock.fastForward(6_000);
  await page.waitForFunction(()=>window.trailingOverviewApplied);assert.ok(overviewReads>trailingBefore);
  await page.close();
  // A new page isolates periodic fallback from the prior mutation's trailing
  // read and its in-flight async interval. A request-start counter alone cannot
  // establish completion before advancing the clock by another two minutes.
  const legacy=await context.newPage();legacy.on('pageerror',error=>errors.push(error.message));
  await legacy.clock.install();
  const initialReads=['/status','/api/overview'].map(path=>legacy.waitForResponse(response=>new URL(response.url()).pathname===path));
  await legacy.goto(url+'/backstage');
  for(const response of await Promise.all(initialReads))await response.finished();
  await legacy.locator('#back-title').waitFor();
  await legacy.waitForFunction(async()=>Boolean((await import('/assets/js/store.js')).state.overview));
  const periodic=legacy.waitForResponse(response=>new URL(response.url()).pathname==='/api/overview');
  await legacy.clock.fastForward(31_000);
  const periodicResponse=await periodic;await periodicResponse.finished();assert.equal(periodicResponse.status(),200);
  await legacy.close();
  ok("old backstage responses without combined overview retain periodic count refresh");
  // Isolated module harness: shared ownership and image scheduler without app traffic.
  const isolated=await context.newPage();
  await isolated.route('**/performance-harness',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><body><main id="images"></main></body>'}));
  await isolated.goto(url+'/performance-harness');
  const shared=await isolated.evaluate(async()=>{const {api}=await import('/assets/js/api.js');const a=new AbortController(),b=new AbortController();const one=api.prefetchDetail(901,{signal:a.signal}).catch(error=>error.name);const two=api.detail(901,{signal:b.signal});a.abort();return [await one,(await two).id,window.fetchAborts.filter(path=>path.includes('/901/reading')).length];});
  assert.deepEqual(shared,['AbortError',901,0]);assert.equal(readingCalls.filter(id=>id===901).length,1);
  const abandoned=await isolated.evaluate(async()=>{const {api}=await import('/assets/js/api.js');const a=new AbortController();const read=api.detail(902,{signal:a.signal}).catch(error=>error.name);a.abort();return [await read,window.fetchAborts.some(path=>path.includes('/902/reading'))];});
  assert.deepEqual(abandoned,['AbortError',true]);ok("shared reading survives one consumer leaving; last consumer cancels transport");
  await isolated.evaluate(async()=>{const {api}=await import('/assets/js/api.js');const {mergeItem}=await import('/assets/js/store.js');mergeItem(await api.detail(903));});
  const readBefore=readingCalls.length;
  await isolated.evaluate(async()=>{const {api}=await import('/assets/js/api.js');await api.detail(903);await api.detail(903);});
  assert.equal(readingCalls.length,readBefore);
  await isolated.evaluate(async()=>{const {api}=await import('/assets/js/api.js');const {getItem}=await import('/assets/js/store.js');getItem(903).cache_identity.body_revision++;await api.detail(903);await api.detailFresh(903);});
  assert.equal(readingCalls.length,readBefore+2);ok('reopening reuses the full body without HTTP; changed revision and explicit refresh fetch again');
  let imageStarts=0;
  await isolated.route('**/api/images/**',async route=>{imageStarts++;await pause(250);return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"><rect width="30" height="30" fill="blue"/></svg>'}).catch(()=>{});});
  await isolated.evaluate(async()=>{const loader=await import('/assets/js/image-loader.js');loader.prioritizeReading(true);for(let i=0;i<6;i++){const img=document.createElement('img');img.width=30;img.height=30;document.querySelector('#images').append(img);loader.queueImage(img,'/api/images/'+i+'?privacy=1&size=160');}const off=document.createElement('img');off.style.cssText='position:absolute;top:10000px';document.body.append(off);loader.queueImage(off,'/api/images/offscreen');});
  await pause(100);assert.equal(imageStarts,0);
  await isolated.evaluate(async()=>{(await import('/assets/js/image-loader.js')).prioritizeReading(false);});await wait(()=>imageStarts===2);
  assert.equal(await isolated.evaluate(async()=>(await import('/assets/js/image-loader.js')).imageQueueStats().active),2);
  await isolated.evaluate(()=>document.querySelector('#images').replaceChildren());await pause(350);
  assert.equal(imageStarts,2);assert.equal(await isolated.evaluate(async()=>(await import('/assets/js/image-loader.js')).imageQueueStats().active),0);
  ok("body priority pauses images; visible queue caps at two and removed images abort");
  await isolated.evaluate(async()=>{const img=document.createElement('img');img.width=30;img.height=30;document.querySelector('#images').append(img);(await import('/assets/js/image-loader.js')).queueImage(img,'/api/images/finish');});
  await isolated.waitForFunction(()=>document.querySelector('#images img')?.naturalWidth>0);
  await isolated.evaluate(()=>{window.reusableImage=document.querySelector('#images img');window.previousImageURL=window.reusableImage.src;document.querySelector('#images').replaceChildren();});await pause(50);assert.equal(await isolated.evaluate(()=>window.objectRevokes),1);
  ok("loaded image object URL is revoked when its DOM consumer is removed");
  const startsBeforeReconnect=imageStarts;
  await isolated.evaluate(async()=>{document.querySelector('#images').append(window.reusableImage);(await import('/assets/js/image-loader.js')).resumeImage(window.reusableImage);});
  await isolated.waitForFunction(()=>window.reusableImage.src!==window.previousImageURL&&window.reusableImage.naturalWidth>0);assert.equal(imageStarts,startsBeforeReconnect);
  ok('reconciled rows recreate revoked image URLs from bounded cached bytes');
  const imageBefore=imageStarts;
  await isolated.evaluate(async()=>{const img=document.createElement('img');img.width=30;img.height=30;document.querySelector('#images').append(img);(await import('/assets/js/image-loader.js')).queueImage(img,'/api/images/finish');});
  await isolated.waitForFunction(()=>document.querySelector('#images img')?.naturalWidth>0);assert.equal(imageStarts,imageBefore);
  await isolated.evaluate(async()=>{(await import('/assets/js/store.js')).emit('account:changed');document.querySelector('#images').replaceChildren();const img=document.createElement('img');img.width=30;img.height=30;document.querySelector('#images').append(img);(await import('/assets/js/image-loader.js')).queueImage(img,'/api/images/finish');});
  await isolated.waitForFunction(()=>document.querySelector('#images img')?.naturalWidth>0);assert.equal(imageStarts,imageBefore+1);ok('reopening reuses image bytes without HTTP; account change clears private media');
  assert.deepEqual(errors,[]);ok("frontend scheduling produces no page exceptions");
  console.log(`${checks}/${checks} performance browser checks passed`);
}finally{await context.close();await browser.close();server.close();}
